// Generated by gencpp from file bno055_usb_stick_msgs/EulerAngles.msg
// DO NOT EDIT!


#ifndef BNO055_USB_STICK_MSGS_MESSAGE_EULERANGLES_H
#define BNO055_USB_STICK_MSGS_MESSAGE_EULERANGLES_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace bno055_usb_stick_msgs
{
template <class ContainerAllocator>
struct EulerAngles_
{
  typedef EulerAngles_<ContainerAllocator> Type;

  EulerAngles_()
    : heading(0.0)
    , roll(0.0)
    , pitch(0.0)  {
    }
  EulerAngles_(const ContainerAllocator& _alloc)
    : heading(0.0)
    , roll(0.0)
    , pitch(0.0)  {
  (void)_alloc;
    }



   typedef double _heading_type;
  _heading_type heading;

   typedef double _roll_type;
  _roll_type roll;

   typedef double _pitch_type;
  _pitch_type pitch;





  typedef boost::shared_ptr< ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> const> ConstPtr;

}; // struct EulerAngles_

typedef ::bno055_usb_stick_msgs::EulerAngles_<std::allocator<void> > EulerAngles;

typedef boost::shared_ptr< ::bno055_usb_stick_msgs::EulerAngles > EulerAnglesPtr;
typedef boost::shared_ptr< ::bno055_usb_stick_msgs::EulerAngles const> EulerAnglesConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator1> & lhs, const ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator2> & rhs)
{
  return lhs.heading == rhs.heading &&
    lhs.roll == rhs.roll &&
    lhs.pitch == rhs.pitch;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator1> & lhs, const ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace bno055_usb_stick_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "2cfcb5286131de123be05c39311011e6";
  }

  static const char* value(const ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x2cfcb5286131de12ULL;
  static const uint64_t static_value2 = 0x3be05c39311011e6ULL;
};

template<class ContainerAllocator>
struct DataType< ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bno055_usb_stick_msgs/EulerAngles";
  }

  static const char* value(const ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float64 heading\n"
"float64 roll\n"
"float64 pitch\n"
;
  }

  static const char* value(const ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.heading);
      stream.next(m.roll);
      stream.next(m.pitch);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct EulerAngles_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::bno055_usb_stick_msgs::EulerAngles_<ContainerAllocator>& v)
  {
    s << indent << "heading: ";
    Printer<double>::stream(s, indent + "  ", v.heading);
    s << indent << "roll: ";
    Printer<double>::stream(s, indent + "  ", v.roll);
    s << indent << "pitch: ";
    Printer<double>::stream(s, indent + "  ", v.pitch);
  }
};

} // namespace message_operations
} // namespace ros

#endif // BNO055_USB_STICK_MSGS_MESSAGE_EULERANGLES_H
